config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :states
  resources :cities
  resources :users
  get "user?Id=", :to => "user#new"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :users
  validates :name, presence: true
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    has_many :users
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :state
    belongs_to :city
    validates :username, presence: true
    validates :gender, presence: true
    validates :email, presence: true
    validates :hobby, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def index
        @cities = City.order(:state_id)
    end

    def new
        @city = City.new
    end

    def create
        @city = City.new(city_params)
        if @city.save
            redirect_to cities_path
        else
            render :new
        end
    end

    def edit
        @city = City.find(params[:id])
    end

    def update
        @city = City.find(params[:id])
        if @city.update(city_params)
            redirect_to cities_path
        else
            render :edit
        end
    end

    def destroy
        @city = City.find(params[:id])
        @city.destroy
        redirect_to cities_path, status: :see_other
    end

    private
    def city_params
      params.require(:city).permit(:state_id, :name)
    end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
    def index
        @states = State.order(:id)
    end
    
    def new
        @state = State.new
    end
    
    def create
        @state = State.new(state_params)
        if @state.save
            redirect_to states_path
        else
            render :new
        end
    end

    def edit
        @state = State.find(params[:id])
    end

    def update
        @state = State.find(params[:id])
        if @state.update(state_params)
            redirect_to states_path
        else
            render :edit
        end
    end

    def destroy
        @state = State.find(params[:id])
        @state.destroy
        redirect_to states_path, status: :see_other
    end

    private
    def state_params
      params.require(:state).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.order(:id)
        @states = State.all
        @cities = City.all
    end

    def new
        @user = User.new
        # @stateid = params[:id]
        # puts @stateid.inspect
        # @cities = State.find(6).cities
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to users_path
        else
            render :new
        end
    end
    
    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to users_path
        else
            render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path, status: :see_other
    end

    private
    def user_params
      params.require(:user).permit(:username, :gender, :email, :state_id, :city_id, :hobby => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/edit.html.erb
<br>
<h1>Edit City Details </h1><br>
<%= form_with model: @city do |form| %>
    
    <div style="color:red;">
        <% @city.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </div><br>
    
    <div>
        <%= form.label :name, "Your City Name :- " %>
        <%= form.text_field :name %><br>
    </div><br>
    
    <div>   
        <%= form.submit %>
    </div>
    
<% end %>

app/views/cities/index.html.erb
<br>
<%= link_to "=>Add New City", new_city_path %><br><br>
<h1>Current Cities :-  </h1><br>
<table border=2 class="table table-success table-striped table-bordered border-dark">
    <tr>
        <th>ID</th>
        <th>State Name</th>
        <th>City Name</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <% @cities.each do |city| %>
        <tr>
            <td><%= city.id %></td>
            <td><%= State.find(city.state_id).name %></td>
            <td><%= city.name %></td>
            <td><%= link_to "Edit", edit_city_path(city)%></td>
            <td><%= link_to "Destroy", city_path(city),  data: { turbo_method: :delete, turbo_confirm: "Are you Sure ?" } %></td>
        </tr>
    <% end %>    
</table>

app/views/cities/new.html.erb
<br>
<h1> New City </h1>
<br>
<%= form_with model: @city do |form| %>
    
    <div style="color:red;">
        <% @city.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </div><br>
    
    <div>
        <%= form.label :state_id, "Select Your State :- " %>
        <%= form.collection_select :state_id, State.order(:id), :id, :name %>
    </div><br>
    
    <div>
        <%= form.label :name, "Enter Your City Name :- " %>
        <%= form.text_field :name %>
    </div><br><br>

    <div>   
        <%= form.submit %>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsdemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/states/edit.html.erb
<br>
<h1>Edit State Details </h1><br>
<%= form_with model: @state do |form| %>
    
    <div style="color:red;">
        <% @state.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </div><br>

    <div>
        <%= form.label :name, "Enter Your State Name :- " %>
        <%= form.text_field :name %><br>
    </div><br>

    <div>   
        <%= form.submit %>
    </div>

<% end %>

app/views/states/index.html.erb
<br>
<%= link_to "=> Add New State", new_state_path %><br><br>
<h1>Current States :- </h1><br>
<table border=2 class="table table-success table-striped table-bordered border-dark" >
    <tr>
        <th>ID</th>
        <th>State_name</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <% @states.each do |state| %>
        <tr>
            <td><%= state.id %></td>
            <td><%= state.name %></td>
            <td><%= link_to "Edit", edit_state_path(state)%></td>
            <td><%= link_to "Destroy", state_path(state),  data: { turbo_method: :delete, turbo_confirm: "Are you Sure ?" } %></td>
        </tr>
    <% end %>
</table>


    

app/views/states/new.html.erb
<h1> New State </h1>
<br>
<%= form_with model: @state do |form| %>
    
    <div style="color:red;">
        <% @state.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </div><br>
    
    <div>
        <%= form.label :name, "Enter Your State Name :- " %>
        <%= form.text_field :name %>
    </div><br><br>
    
    <div>   
        <%= form.submit %>
    </div>

<% end %>

app/views/users/edit.html.erb
<br>
<h1>Edit User</h1><br>
<%= form_with model: @user do |form| %>
    
    <div style="color:red;">
        <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </div><br>
    
    <div>
        <%= form.label :username, "Enter Your Username :- " %>
        <%= form.text_field :username %><br>
    </div><br>
    
    <div>
        <%= form.label :gender, "Select Your Gender :- " %>
        <%= form.radio_button :gender, "male" %>
        <%= form.label :gender_male, "Male"%>
        <%= form.radio_button :gender, "female" %>
        <%= form.label :gender_female, "Female" %><br>
    </div><br>
    
    <div>
        <%= form.label :Email, "Enter Your Email :- "%>
        <%= form.text_field :email %><br>
    </div><br>

    <div>
        <%= form.label :state, "Select Your State :- " %>
        <%= form.collection_select :state_id, State.order(:id), :id, :name %><br>
    </div><br>

    <div>
        <%= form.label :city, "Select Your City :- "%>
        <%= form.collection_select :city_id, City.order(:id), :id, :name %><br>
    </div><br>

    <div>
        <%= form.label :select_hobby, "Select Your Hobby :- "%>
        <%= form.check_box :hobby, {multiple: true}, "reading", nil %>
        <%= form.label :check_reading, "Reading" %>
        <%= form.check_box :hobby, {multiple: true}, "sport", nil %>
        <%= form.label :check_sport, "Sport" %>
        <%= form.check_box :hobby, {multiple: true}, "travelling", nil %>
        <%= form.label :check_travelling, "Travelling" %>
    </div><br>

    <div>   
        <%= form.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<br>
<%= link_to " => Add New User", new_user_path %>
<br><br>
<h1>Current Users List :- </h1><br>
<table border=2 class="table table-success table-striped table-bordered border-dark" >
    <tr>
        <th>ID</th>
        <th>UserName</th>
        <th>Gender</th>
        <th>Email</th>
        <th>State</th>
        <th>City</th>
        <th>Hobby</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.gender %></td>
            <td><%= user.email %></td>
            <td><%= State.find(user.state_id).name %></td>
            <td><%= City.find(user.city_id).name %></td>
            <td><%= user.hobby %></td>
            <td><%= link_to "Edit", edit_user_path(user)%></td>
            <td><%= link_to "Destroy", user_path(user),  data: { turbo_method: :delete, turbo_confirm: "Are you Sure ?" } %></td>
        </tr>
    <% end %>
</table>
    

app/views/users/new.html.erb
<br><br>
<h1> New User :- </h1>
<br>

<%= form_with model: @user , data: {turbo: false}  do |form| %>
    
    <div style="color:red;">
        <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </div><br>
    
    <div>
        <%= form.label :username, "Enter Your Username :- " %>
        <%= form.text_field :username %>
    </div><br>
    
    <div>
        <%= form.label :gender, "Select Your Gender :- " %>
        <%= form.radio_button :gender, "male" %>
        <%= form.label :gender_male, "Male"%>
        <%= form.radio_button :gender, "female" %>
        <%= form.label :gender_female, "Female" %>
    </div><br>
    
    <div>
        <%= form.label :Email, "Enter Your Email :- "%>
        <%= form.text_field :email %>
    </div><br>

    <div>
        <%= form.label :state_id, "Select Your State :- "%>
        <%= form.collection_select :state_id, State.order(:id), :id, :name %>
    </div><br>
    
    <div>
        <%= form.label :city_id, "Select Your City :- "%>
        <%#= form.collection_select :city, City.all, :city_name, :city_name %>
        <%#= form.collection_select :city_id, City.order(:id), :id, :city_name %>
        <%= select_tag 'user[city_id]', options_from_collection_for_select(City.all, :id, :name) %>
    </div><br>

    <div>
        <%= form.label :select_hobby, "Select Your Hobby :- "%>
        <%= form.check_box :hobby, {multiple: true}, "reading", nil %>
        <%= form.label :check_reading, "Reading" %>
        <%= form.check_box :hobby, {multiple: true}, "sport", nil %>
        <%= form.label :check_sport, "Sport" %>
        <%= form.check_box :hobby, {multiple: true}, "travelling", nil %>
        <%= form.label :check_travelling, "Travelling" %>
    </div><br>

    <div>   
        <%= form.submit %>
    </div>
<% end %>